- hosts: all
  vars:
    - image: ferdicorpina/web_nginx
  tasks:
    - name: install python-docker di centos
      yum:
        name: "{{ item }}"
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == 'RedHat'

    - name: install python-docker di ubuntu
      apt:
        name: "{{ item }}"
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == 'Debian'

    - name: pull image
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: dun container
      docker_container:
        name: web_nginx_ansible
        image: "{{ image }}"
        state: started
        published_ports:
          - 10000:80
        recreate: yes
